//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gadget_freak_backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogLogging
    {
        public int Id { get; set; }
        public int BlogId { get; set; }
        public System.DateTime LogDate { get; set; }
        public string UserId { get; set; }
    
        public virtual BlogPost BlogPost { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
