//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gadget_freak_backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogPostCOmments
    {
        public int Id { get; set; }
        public int PostId { get; set; }
        public string UserId { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual BlogPost BlogPost { get; set; }
    }
}
